baseURL = ""
languageCode = "fr-fr"
paginate = 6
theme = "portio"
title = "Klervi, Psychologue"
# Main Menu
[[menu.main]]
name = "Accueil"
url = "#home"
weight = 1
[[menu.main]]
name = "Parcours professionnel"
url = "#resume"
weight = 4
[[menu.main]]
name = "Consultations"
url = "#service"
weight = 5
[[menu.main]]
name = "Infos pratiques"
url = "#info"
weight = 7

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Latest Article"
url = "#"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Portio 2020"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
address = "30 rue de la Blordière Résidence la Clé des Champs – immeuble Les merisiers 44400 REZE"
email = "klervi.isidor@wanadoo.fr"
openingHours = "De lundi à jeudi de 9h à 17h..."
price = "50€ la séance d'environ 45min"
phone = "07.83.24.67.92"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/"
weight = 2
[[params.social]]
icon = "fa-pinterest-square"
url = "https://www.pinterest.com/"
weight = 3
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/"
weight = 4
